dist: xenial
language: python
sudo: enabled
notifications:
    email: false
python:
  - "3.5"

before_install:
  # install libvmi dependencies
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-libvirt

install:
  - pip install pycodestyle

script:
  - pycodestyle --show-source -v
  - python -m oswatcher.capture
