-- MySQL Script generated by MySQL Workbench
-- dim. 09 oct. 2016 14:05:40 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema oswatcher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS oswatcher DEFAULT CHARACTER SET utf8 ;
USE oswatcher ;

CREATE TABLE IF NOT EXISTS oswatcher.os (
  id INT NOT NULL,
  name MEDIUMTEXT NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS oswatcher.filesystem (
  vm_id INT NOT NULL,
  inode INT NOT NULL,
  path INTEGER[] NOT NULL,
  filename MEDIUMTEXT NOT NULL,
  PRIMARY KEY (vm_id, inode),
  CONSTRAINT fk_filesystem_vm
    FOREIGN KEY (vm_id)
    REFERENCES oswatcher.OS (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS oswatcher.inode (
  filesystem_vm_id INT NOT NULL,
  filesystem_inode INT NOT NULL,
  PRIMARY KEY (filesystem_vm_id, filesystem_inode),
  CONSTRAINT fk_inode_filesystem1
    FOREIGN KEY (filesystem_vm_id , filesystem_inode)
    REFERENCES oswatcher.filesystem (vm_id , inode)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
