name: Lint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Lint with flake8
      run: |
        pip install flake8
        # ignore E402: Rekall redefining the root logger, we need a hack to avoid that
        # ignore W503: a bug flake8
        flake8 --show-source --statistics --max-line-length=127 --ignore=E402,W503 oswatcher
        flake8 --show-source --statistics --max-line-length=127 --ignore=E402,W503 hooks